### ISSUE TITLE
Right clicking links

### ISSUE THREAD

**Issue by benpate** [EmissarySocial/bandwagon#139]
Many links only use `hx-get`, and not `href`, so they can't be right clicked.

**Comment by benpate** [comment]
Have done a sweep though this, which should fix the issue.  May still need some manual testing.

**Comment by ethicalrevolution** [comment]
Woo, I can see it working in many places. I've found a few places where it's still not:

1. The album links on the artist page (e.g. 'Think Twice' thumbnail and text on https://bandwagon.fm/@SecretDeal)
2. Clicking the artist name when on a song or album page (e.g. clicking 'Secret Deal' on https://bandwagon.fm/67c56c6c84cf969049294360 or https://bandwagon.fm/67c56cc36cc91ceba364e238)
3. Clicking the album name when on the song page e.g. 'Think Twice' (next to 'Secret Deal') on https://bandwagon.fm/67c56cc36cc91ceba364e238
4. Any of the main menu links (Home, Discover, News, About, Profile, Inbox) from any page.

**Comment by benpate** [comment]
Gotcha.  Thank you for this list.  I'll have to look at each one individually, but they should be easy to knock out.

Ironically, I think part of the problem is some "accessibility" advice I took from one of the highly opinionated sources out there in the wild.  At the end of the day, I think I'm going to scrap their exotic solution and just go back to basic link tags :)

**Comment by benpate** [comment]
What browser are you using?  Literally all of these are working for me using Chrome, Firefox, and Safari on macOS.

Is it possible these pages were cached on your machine?

**Comment by ethicalrevolution** [comment]
I tried on Firefox on linux, Firefox on iOS and Firefox on OSX. I’ve cleared cache too.

**Comment by benpate** [comment]
Pushing an update for this now.  Now all of these images/elements should be right-clickable, not just the labels.

Two small exceptions:

1) Its touch to make table rows right-clickable.  So these usually have a link (that is right-clickable) but a shortcut that lets you left-click the entire row.  We may be able to improve this in the future, but it would probably take different code that I have right now to make it go.

2)  are elements that are `buttons` -- that affect behavior on the page without navigating to a new page.  "Play" buttons are an example of this, but there are many others throughout the site.

This is live now, but I'm going to put it in "Waiting" because it needs more QA than others :)

**Comment by ethicalrevolution** [comment]
Testing on iOS only at the mo … Number 1 on my list of 4 above now works, but 2, 3 and 4 are all still the same.

**Comment by benpate** [comment]
Sorry it took me a minute to get back to this.  Here's a video of all of the links working correctly.  Do you see the same?

https://www.dropbox.com/scl/fi/k45x9knmyjd8vgqlx0xb5/Screen-Recording-2025-04-07-at-9.44.05-AM.mov?rlkey=67sqmnjijalccz59mpvvhfs9p&dl=0

**Comment by ethicalrevolution** [comment]
Ah, I think the difference here is that you're literally right clicking and then clicking 'open in new tab'. It seems to work like that. But when holding command and click on a desktop (which should open in a new tab and does on all other sites) or long click on a tablet to bring up 'open in new tab' it still opens the link in the current window.

**Comment by benpate** [comment]
Okay. Thanks for the clarification here. I’ve never opened new tabs with command +click, but I can look to see what’s causing the issue.

**Comment by benpate** [comment]
I have something ready to go for this.  It turns out to be a system-wide change, so I want to sit on it for a bit to make sure I'm not breaking anything unexpectedly.

One piece of good news is that (strangely) this also moves us closer to the media player upgrades that I've wanted to do - #18 - which requires some fancy logic on the browser to continue playing audio even when you navigate to a new page. Well, this update includes that fancy logic.  Yay!
